name: malina_mobile_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  go_router: ^7.0.2
  intl: ^0.18.0
  flutter_screenutil: ^5.7.0
  equatable: ^2.0.5
  http: ^0.13.5
  hive: ^2.2.3
  form_validator: ^2.1.1
  path_provider: ^2.0.14
  hive_flutter: ^1.1.0
  keyboard_dismisser: ^3.0.0
  expansion_tile_card: ^2.0.0
  syncfusion_flutter_calendar: ^21.1.37
  dropdown_button2: ^2.0.0
  intl_phone_number_input: ^0.7.3+1
  buttons_tabbar: ^1.3.6
  animations: ^2.0.7
  flutter_rating_stars: ^1.0.3+4
  carousel_slider: ^4.2.1
  yandex_mapkit: ^3.3.3
  geolocator: ^9.0.2
  uuid: ^3.0.7
  collection: any
  device_info_plus: ^9.0.1
  pin_code_fields: ^7.4.0
  syncfusion_flutter_datepicker: ^21.2.5
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.0"
  flutter_native_splash: ^2.2.19
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo.png"

flutter_native_splash:
  color: "#F72055"
  image: "assets/images/logo/launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/not_found/
    - assets/images/emoji/
    - assets/images/logo/
    - assets/images/main/
    - assets/images/profile/
    - assets/icons/
    - assets/icons/barbershop/
    - assets/icons/notifications/
    - assets/icons/restaurant/
    - assets/icons/profile/
    - assets/icons/navbar/
    - assets/icons/social/
    - assets/icons/main/
    - assets/debug/
    - assets/debug/barbershops/
    - assets/debug/products/
    - assets/debug/specialist/
    - assets/debug/ads/
    - assets/debug/foods/
    - assets/debug/places/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 100